function [] = master_function()
%% Details for loading data from website
product = '3day';   %Temporal resolution
index = 'gcc';      %Index
site = ...  %***sitename, see gallery of sites
ROI = ...   %***ROI name, see site page for site you're interested in

%% Load time series from PhenoCam web site
[years, T, Y] = GCC_load(site, ROI, product, index);
%Could save output from these and other functions, but this is just for
%illustrative use

%% Do curve fit
% [params, modelT, modelY, cut_off_dates, fhandle,...
%     jacobian, resnorm] = ...
%     VI_curve(T, Y, years, model_name);

%% Estimate phenology dates
% [six_dates] = ...
%     getPhenoDates(years, model_name, params, modelT, modelY,...
%     T, Y,...
%     date_method, percentiles,...
%     cut_off_dates,...
%     fhandle, site, ROI, index);

%% Monte Carlo
% getPhenoDatesMC(years, model_name, params, modelT, modelY,...
% T, Y,...
% date_method, percentiles,...
% cut_off_dates,...
% fhandle, site, ROI, index,...
% jacobian, resnorm);

%% Save phenology dates
% save(['./output/' site '_' ROI '_' model_name '_dates'],...
%     'six_dates', 'modelT', 'modelY',...
%     'years', 'model_name', 'T', 'Y');
%Also as csv

%% Plot all years
% phenoPlot(years, index, T, Y, modelT, modelY, six_dates,...
%     model_name, date_method, site, ROI);